### ISSUE TITLE
[Error][v0.4.9] Expected instance of DRep

### ISSUE THREAD

**Issue by AlexDochioiu** [Anastasia-Labs/lucid-evolution#428]
I am currently debugging some issue returning "Error: expected instance of DRep" when sending always abstain: 

```ts
export const DREP_ALWAYS_ABSTAIN: DRep = { __typename: "AlwaysAbstain" };
// ...
// redacted code
// ...
tx.delegate.VoteToDRep(stakingAddress.bech32(), DREP_ALWAYS_ABSTAIN);
```

I believe this issue appeared when we updated to 0.4.9 from 0.4.4

**Comment by AlexDochioiu** [comment]
Also, as a suggestion, it may be good to export `AlwaysAbstain` and `AlwaysNoConfidence` and  directly from the SDK. Currently they are not.

<img width="484" alt="image" src="https://github.com/user-attachments/assets/21a582b8-ec77-4e1d-b643-3db11f22a460">

**Comment by AlexDochioiu** [comment]
More info: 

```
at async Object.<anonymous> (file:///usr/src/app/dist/routes_auto/wallet/tx_prepare_v4.js:31:32) {
  innerError: (FiberFailure) RunTimeError: Error: expected instance of DRep
      at file:///usr/src/app/node_modules/@lucid-evolution/lucid/dist/index.js:1407:44
      at file:///usr/src/app/node_modules/effect/dist/esm/internal/core-effect.js:71:16,
  title: undefined,
```

**Comment by hadelive** [comment]
> Also, as a suggestion, it may be good to export `AlwaysAbstain` and `AlwaysNoConfidence` directly from the SDK. Currently they are not.
> 
> <img alt="image" width="484" src="https://private-user-images.githubusercontent.com/38853913/390856332-21a582b8-ec77-4e1d-b643-3db11f22a460.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5ODQwNjgsIm5iZiI6MTczMjk4Mzc2OCwicGF0aCI6Ii8zODg1MzkxMy8zOTA4NTYzMzItMjFhNTgyYjgtZWM3Ny00ZTFkLWI2NDMtM2RiMTFmMjJhNDYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDE2MjI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiZjU5ZWIzMTI3YTRlMmQ1MzFkYTZjOGMzMjMyODhhZGZkNDE1OTM4ZGZiYjNkZDI2NjUwMWFiNmM2MjE3YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tvVXWnio28pdvr94fvGUsq8C-m3zv5r-HjUpmbiF8mE">

It has already been exported.

**Comment by hadelive** [comment]
> More info:
> 
> ```
> at async Object.<anonymous> (file:///usr/src/app/dist/routes_auto/wallet/tx_prepare_v4.js:31:32) {
>   innerError: (FiberFailure) RunTimeError: Error: expected instance of DRep
>       at file:///usr/src/app/node_modules/@lucid-evolution/lucid/dist/index.js:1407:44
>       at file:///usr/src/app/node_modules/effect/dist/esm/internal/core-effect.js:71:16,
>   title: undefined,
> ```

This error originates from a CML function.

**Comment by AlexDochioiu** [comment]
> > More info:
> > ```
> > at async Object.<anonymous> (file:///usr/src/app/dist/routes_auto/wallet/tx_prepare_v4.js:31:32) {
> >   innerError: (FiberFailure) RunTimeError: Error: expected instance of DRep
> >       at file:///usr/src/app/node_modules/@lucid-evolution/lucid/dist/index.js:1407:44
> >       at file:///usr/src/app/node_modules/effect/dist/esm/internal/core-effect.js:71:16,
> >   title: undefined,
> > ```
> 
> This error originates from a CML function.

Hmm. Were you able to reproduce it? Is it a bug in CML? Or a mis-usage on our end?

**Comment by hadelive** [comment]
I’m investigating the cause of this failure in the browser environment.
```
CML.SingleCertificateBuilder.new(
  CML.Certificate.new_stake_vote_reg_deleg_cert(
    credential,
    CML.Ed25519KeyHash.from_bech32(poolId),
    cmlDRep,
    config.lucidConfig.protocolParameters.keyDeposit,
  ),
);
```

**Comment by AlexDochioiu** [comment]
In our case the reported issue is in node env (nodejs typescript server)

**Comment by hadelive** [comment]
this link, right?
https://github.com/ariady-putra-emurgo/aiken_staking_validator/blob/e592f8f52935308b94e32d4dbe3bca5a6c5c3972/offchain/components/Dashboard.tsx#L102-L109

**Comment by hadelive** [comment]
this link, right?

https://github.com/ariady-putra-emurgo/aiken_staking_validator/blob/e592f8f52935308b94e32d4dbe3bca5a6c5c3972/offchain/components/Dashboard.tsx#L102-L109

**Comment by hadelive** [comment]
> In our case the reported issue is in node env (nodejs typescript server)

I try this one and get the tx https://preprod.cexplorer.io/tx/98c0fd8b7f4bea345bff2ba7219263da826e9a7ada278ea9f45965fc38f31943/governance#data
https://github.com/Anastasia-Labs/lucid-evolution/blob/main/packages/lucid/test/specs/governance.ts#L232-L255

**Comment by AlexDochioiu** [comment]
> this link, right?
> 
> https://github.com/ariady-putra-emurgo/aiken_staking_validator/blob/e592f8f52935308b94e32d4dbe3bca5a6c5c3972/offchain/components/Dashboard.tsx#L102-L109

I am not sure what this is? Was it sent by mistake? We don’t use aiken/etc.

**Comment by AlexDochioiu** [comment]
> > this link, right?
> > https://github.com/ariady-putra-emurgo/aiken_staking_validator/blob/e592f8f52935308b94e32d4dbe3bca5a6c5c3972/offchain/components/Dashboard.tsx#L102-L109
> 
> I am not sure what this is? Was it sent by mistake? We don’t use aiken/etc.

I believe 

> > In our case the reported issue is in node env (nodejs typescript server)
> 
> I try this one and get the tx https://preprod.cexplorer.io/tx/98c0fd8b7f4bea345bff2ba7219263da826e9a7ada278ea9f45965fc38f31943/governance#data https://github.com/Anastasia-Labs/lucid-evolution/blob/main/packages/lucid/test/specs/governance.ts#L232-L255

I see in this case the delegation was done to an existing DRep. I believe in our case it’s only problematic when delegating to AlwaysAbstain

**Comment by hadelive** [comment]
> > this link, right?
> > https://github.com/ariady-putra-emurgo/aiken_staking_validator/blob/e592f8f52935308b94e32d4dbe3bca5a6c5c3972/offchain/components/Dashboard.tsx#L102-L109
> 
> I am not sure what this is? Was it sent by mistake? We don’t use aiken/etc in VESPR

Ahh. Another dev `Area D`

**Comment by hadelive** [comment]
> > > In our case the reported issue is in node env (nodejs typescript server)
> > 
> > 
> > I try this one and get the tx https://preprod.cexplorer.io/tx/98c0fd8b7f4bea345bff2ba7219263da826e9a7ada278ea9f45965fc38f31943/governance#data https://github.com/Anastasia-Labs/lucid-evolution/blob/main/packages/lucid/test/specs/governance.ts#L232-L255
> 
> I see in this case the delegation was done to an existing DRep (using drep id). I believe in our case it’s only problematic when delegating to AlwaysAbstain (which is not of DRep type, and where the issue seems to come from ad far as the logs indicate?)

You mean like this

https://github.com/Anastasia-Labs/lucid-evolution/blob/main/packages/lucid/test/specs/governance.ts#L141-L159

**Comment by hadelive** [comment]
> > > In our case the reported issue is in node env (nodejs typescript server)
> > 
> > 
> > I try this one and get the tx https://preprod.cexplorer.io/tx/98c0fd8b7f4bea345bff2ba7219263da826e9a7ada278ea9f45965fc38f31943/governance#data https://github.com/Anastasia-Labs/lucid-evolution/blob/main/packages/lucid/test/specs/governance.ts#L232-L255
> 
> I see in this case the delegation was done to an existing DRep (using drep id). I believe in our case it’s only problematic when delegating to AlwaysAbstain (which is not of DRep type, and where the issue seems to come from ad far as the logs indicate?)

Could you try it again?
It works in the CI: 
https://github.com/Anastasia-Labs/lucid-evolution/actions/runs/12091117220/job/33719111647#step:10:494
(https://preprod.cexplorer.io/tx/f0e9a65886a622b0526303931c1ffba6d5f851c0996b20f8ae074985af6d47a6/governance#data)

**Comment by AlexDochioiu** [comment]
> > > > In our case the reported issue is in node env (nodejs typescript server)
> > > 
> > > 
> > > I try this one and get the tx https://preprod.cexplorer.io/tx/98c0fd8b7f4bea345bff2ba7219263da826e9a7ada278ea9f45965fc38f31943/governance#data https://github.com/Anastasia-Labs/lucid-evolution/blob/main/packages/lucid/test/specs/governance.ts#L232-L255
> > 
> > 
> > I see in this case the delegation was done to an existing DRep (using drep id). I believe in our case it’s only problematic when delegating to AlwaysAbstain (which is not of DRep type, and where the issue seems to come from ad far as the logs indicate?)
> 
> You mean like this
> 
> https://github.com/Anastasia-Labs/lucid-evolution/blob/main/packages/lucid/test/specs/governance.ts#L141-L159

Pretty much, yes. Except we always use the ‘delegate.VoteToDrep’ and single certs instead of the composite certificate (because the composite ones are not supported by ledger)

**Comment by hadelive** [comment]
Yep.
For single certs: https://github.com/Anastasia-Labs/lucid-evolution/blob/main/packages/lucid/test/specs/governance.ts#L56-L69

**Comment by AlexDochioiu** [comment]
We never updated to newer than 0.4.4 because of this issue.

**Comment by leo42** [comment]
> We never updated to newer than 0.4.4 because of this issue.

Let me try with 0.4.4 to see if it changes, thanks for the tip

**Comment by leo42** [comment]
Confirmed that 0.4.4 works, whaever is causing this was implemented after 0.4.4

**Comment by AlexDochioiu** [comment]
@leo42 You can easily reproduce it? Cause I couldn't (I just had logs showing it's happening a lot). May be useful to share the code that causes it.

P.s. If it's not too much hassle, would be great if you can identify exactly in which release it was introduced. So far we know that 0.4.4 works and 0.4.9 doesn't. So it was introduced in 0.4.5, 0.4.6, 0.4.7, 0.4.8 or 0.4.9.

Would you be able to easily test them one by one? I'm sure that would help @hadelive pinpoint the issue.

**Comment by leo42** [comment]
> @leo42 You can easily reproduce it? Cause I couldn't (I just had logs showing it's happening a lot). May be useful to share the code that causes it.
> 
> P.s. If it's not too much hassle, would be great if you can identify exactly in which release it was introduced. So far we know that 0.4.4 works and 0.4.9 doesn't. So it was introduced in 0.4.5, 0.4.6, 0.4.7, 0.4.8 or 0.4.9.
> 
> Would you be able to easily test them one by one? I'm sure that would help @hadelive pinpoint the issue.

... we have many braking changes it is tiresome to try all the versions but I will give it a try if I have the time.


I am getting in consistantly in broClan, stumbled on to it while migrating to Lucid-evolution 

this is the last commit before the fix, unfortinetly is a rather larger project so runing a quick isolated test is not very fast.
https://github.com/leo42/BroClanWallet/commit/0002369d03cf4ea88acd764c2c9b6b60024fc2de 

The code that produces the error:
```
 let dRep: DRep 
      if (dRepId === "Abstain") {
        dRep = { __typename: "AlwaysAbstain" } as DRep;
      } else if (dRepId === "NoConfidence") {
        dRep = { __typename: "AlwaysNoConfidence" } as DRep;
      } else {
        dRep = decodeCIP129(dRepId);
      }
      console.log("dRep", dRep)
      const tx = await this.createTemplateTx(signers)

      if (curentDelegation.poolId === pool && curentDelegation.dRepId === dRepId){
        throw new Error('Delegation unchanged');
      } else if (curentDelegation.poolId === null){
        tx.registerStake(rewardAddress) 
      }
      
      tx.collectFrom(this.utxos, LucidEvolution.Data.void())
      // const completedTx = await tx.pay.ToAddress(this.getAddress())
      console.log("dRep", dRep)
      const completedTx = await tx.delegateTo(rewardAddress,pool)
      .delegate.VoteToDRep(rewardAddress,dRep, LucidEvolution.Data.void())
      .complete()
      ```
      
  This is for Multisig wallets and I get the same error on PlutusV3 based wallets.

**Comment by AlexDochioiu** [comment]
```ts
const completedTx = await tx.delegateTo(rewardAddress,pool)
      .delegate.VoteToDRep(rewardAddress,dRep, LucidEvolution.Data.void())
      .complete()
```

Above code stands out to me. We also _**sometimes**_ `delegate.ToPool` as well as `delegate.VoteToDRep` in the same transaction. Maybe the combination of delegate to pool and vote to dRep causes the issue? cc @hadelive 

_Note: We may also `register.Stake` in the same transaction._

**Comment by kunj77** [comment]
+1 I am getting a similar issue. This is what I am doing on preview

` const tx = lucid.newTx();
   const drep2: DRep = { type: "Key", hash: "f91c272236b6528f124bbf42e22c1bcf45bdabdd3d37617e6d8ae93f" }
  tx.delegate.VoteToDRep("stake_test1updadxwkldmplhf9xhwjfg52jtzuvpppg3966yndvnsrqqqv0xfhp", drep2, Data.void())
`

The result is the same if I do 

` const tx = lucid.newTx();
   const drep: DRep = { __typename: "AlwaysAbstain" };
   tx.delegate.VoteToDRep("stake_test1updadxwkldmplhf9xhwjfg52jtzuvpppg3966yndvnsrqqqv0xfhp", drep, Data.void())
`

I tried after removing the redeemer too, the key gets generated properly but building the certificate fails.

**Comment by hadelive** [comment]
> ```ts
> const completedTx = await tx.delegateTo(rewardAddress,pool)
>       .delegate.VoteToDRep(rewardAddress,dRep, LucidEvolution.Data.void())
>       .complete()
> ```
> 
> Above code stands out to me. We also _**sometimes**_ `delegate.ToPool` as well as `delegate.VoteToDRep` in the same transaction. Maybe the combination of delegate to pool and vote to dRep causes the issue? cc @hadelive
> 
> _Note: We may also `register.Stake` in the same transaction._

You mean this `delegate.VoteToPoolAndDRep`
`https://github.com/Anastasia-Labs/lucid-evolution/blob/4e7a777fcfdfc0185140ec85966d5d81f7aa01be/packages/lucid/test/specs/governance.ts#L100C15-L100C32`

**Comment by AlexDochioiu** [comment]
> > ```ts
> > const completedTx = await tx.delegateTo(rewardAddress,pool)
> >       .delegate.VoteToDRep(rewardAddress,dRep, LucidEvolution.Data.void())
> >       .complete()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Above code stands out to me. We also _**sometimes**_ `delegate.ToPool` as well as `delegate.VoteToDRep` in the same transaction. Maybe the combination of delegate to pool and vote to dRep causes the issue? cc @hadelive
> > _Note: We may also `register.Stake` in the same transaction._
> 
> You mean this `delegate.VoteToPoolAndDRep` `https://github.com/Anastasia-Labs/lucid-evolution/blob/4e7a777fcfdfc0185140ec85966d5d81f7aa01be/packages/lucid/test/specs/governance.ts#L100C15-L100C32`

I don’t use the composite certificates because they are not compatible with ledger. I often use 2 separate certs. One for pool delegation and one for drep delegation. Sometimes a third cert for stake registration too.

**Comment by AlexDochioiu** [comment]
@hadelive I see a merge + release has been done, linking this issue. Does this mean this is fixed?

**Comment by hadelive** [comment]
It works with our simple webpack setup [here](https://github.com/Anastasia-Labs/lucid-evolution/pull/405/commits/a36863b68540c8a75a2381679aa42d582d596352)

Could you share your project setup?

**Comment by AlexDochioiu** [comment]
@hadelive I added a comment here with the problematic transaction:

https://github.com/Anastasia-Labs/lucid-evolution/pull/405/commits/a36863b68540c8a75a2381679aa42d582d596352#r1922094847

**Comment by AlexDochioiu** [comment]
> [@hadelive](https://github.com/hadelive) I added a comment here with the problematic transaction:
> 
> [a36863b#diff-14aa4d911826c5cfddc9bbaf6b28f6a76ac8cf7bace1b19d327f8863ceab2804R32-R49](https://github.com/Anastasia-Labs/lucid-evolution/commit/a36863b68540c8a75a2381679aa42d582d596352#diff-14aa4d911826c5cfddc9bbaf6b28f6a76ac8cf7bace1b19d327f8863ceab2804R32-R49)

I think github is playing tricks on me cause I don't see the comment when I open that link. I'll add a screenshot of it instead:

![Image](https://github.com/user-attachments/assets/16aedeb0-68da-4862-823c-9c2cecc6ce58)

**Comment by hadelive** [comment]
Like this?
https://preprod.cardanoscan.io/transaction/3dedd89e1283133d403cf4be5bc55156c10522a7b423c667b45f43ef534da55e?tab=stakecertificates

**Comment by AlexDochioiu** [comment]
> It works with our simple webpack setup [here](https://github.com/Anastasia-Labs/lucid-evolution/pull/405/commits/a36863b68540c8a75a2381679aa42d582d596352)
> 
> Could you share your project setup?

In my case it's nodejs, not browser.

tsconfig.json
```json
{
  "extends": "@tsconfig/node20/tsconfig.json",
  "compilerOptions": {
    "moduleResolution": "node",
    "module": "ES2022",
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "declaration": true,
    "declarationMap": false,
    "experimentalDecorators": true,
    "resolveJsonModule": true,
    "rootDir": "./src",
    "outDir": "dist",
    "baseUrl": ".",
    "paths": {
      "*": ["node_modules/*"]
    },
    "alwaysStrict": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "strictNullChecks": true,
    "esModuleInterop": true,
    "allowJs": true
  },
  "include": ["src/**/*"]
}
```
package.json
```json
{
  "name": "vespr-server",
  "version": "1.4.1",
  "description": "",
  "main": "./dist/server.js",
  "engines": {
    "node": "20.17.0",
    "npm": "11.0.0"
  },
  "type": "module",
  "scripts": {
    "start": "npm run build && node dist/server.js",
    ...
  },
  "repository": {
    "type": "git",
    "url": "redacted"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "redacted"
  },
  "homepage": "redacted",
  "devDependencies": {
    "@tsconfig/node20": "^20.1.4",
    "@types/node": "^20.17.11",
    "ts-node": "^10.9.2",
    "typescript": "^5.7.2",
    ...
  },
  "dependencies": {
    ...
  }
}

```

**Comment by hadelive** [comment]
I add a simple node setup [here](https://github.com/Anastasia-Labs/lucid-evolution/pull/405/commits/5fc8446451ad443903e81af8fcf24b79112d9bfc)

**Comment by kunj77** [comment]
Is the working for anyone? I am still facing the same issue. I took the exact code from the example here https://github.com/Anastasia-Labs/lucid-evolution/pull/405/commits/5fc8446451ad443903e81af8fcf24b79112d9bfc with the latest lucid-evolution version of **0.4.20** but am still getting the same error for preprod

`address :>>  addr_test1qzyypw75ds264s7mdlhu00na2d2fwcywvlwnlshunfnxc27k3kpc8d6ek3w3867f8d9vle6c2vwaklzzy6w482axmags86vlea
rewardAddress :>>  stake_test1urtgmqurkavmghgna0ynkjk0uav9x8wm03pzd82n4wnd75g3t2lzm
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

RunTimeError: Error: expected instance of DRep`

**Comment by AlexDochioiu** [comment]
Hey @solidsnakedev @hadelive . Just tested 0.4.21 and can confirm the issue is not happening anymore 🎊 ! Thank you your work! 🙏🏻
