### ISSUE TITLE
Next js 15.0.3, lucid on server, and webassembly

### ISSUE THREAD

**Issue by kozer** [Anastasia-Labs/lucid-evolution#437]
I'm trying some days now to make things work in latest nextjs and lucid.
What I have noticed, is that for some reason the library tries to find `cardano_multiplatform_lib_bg.wasm`  in a wrong folder, when is used in a 'use server' component.

I ended up with the following `.next.config.ts`

```typescript
/** @type {import('next').NextConfig} */
import path from "path";
import fs from "node:fs";
import { NextConfig } from "next";

const getOutputPath = () => {
  if (process.env.NODE_ENV === "development") {
    return "vendor-chunks";
  }
  return "chunks";
};

const nextConfig: NextConfig = {

  webpack: (config, { isServer }) => {
    config.experiments = {
      asyncWebAssembly: true,
      layers: true,
    };
		const chunkPath = getOutputPath();

    config.optimization.moduleIds = "named";

    if (isServer) {
      // Server-specific externals
      config.externals = [
        ...(config.externals || []),
        "@sidan-lab/sidan-csl-rs-nodejs",
      ];

      // Server-side WASM handling
      config.module.rules.push({
        test: /\.wasm$/,
        type: "asset/resource",
        generator: {
          filename: `${chunkPath}/[name][ext]`,
        },
      });

      // WASM files copy plugin
      config.plugins.push({
        apply: (compiler: {
          hooks: {
            afterEmit: { tap: (arg0: string, arg1: () => void) => void };
          };
        }) => {
          compiler.hooks.afterEmit.tap("CopyWasmFiles", () => {
            const targetDir = path.resolve(
              __dirname,
              ".next",
              "server",
							chunkPath,
            );
            fs.mkdirSync(targetDir, { recursive: true });

            const nodeModulesPath = path.resolve(__dirname, "node_modules");
            const findAndCopyWasm = (dir: fs.PathLike) => {
              const items = fs.readdirSync(dir);
              items.forEach((item) => {
                const fullPath = path.join(dir as string, item);
                if (fs.statSync(fullPath).isDirectory()) {
                  findAndCopyWasm(fullPath);
                } else if (item.endsWith(".wasm")) {
                  const targetPath = path.join(targetDir, item);
                  fs.copyFileSync(fullPath, targetPath);
                }
              });
            };

            try {
              findAndCopyWasm(nodeModulesPath);
            } catch (error) {
              console.error("Error copying WASM files:", error);
            }
          });
        },
      });
    }

    return config;
  },
};

module.exports = nextConfig;
```

What this does, is that it copies all `*.wasm` file under `chunks` folder on `production` environement, and in `vendor-chunks` when someone tries to run the project using `npm run dev`.

Problem is, that I'm trying to deploy in vercel, and although this should have worked ( as it builds successfully using `npm run build` locally ), it fails when it calls the server function with the following error ( taken from Logs tab in vercel dashboard ):

```
 Error: ENOENT: no such file or directory, open '/var/task/.next/server/chunks/cardano_multiplatform_lib_bg.wasm'
    at 77969 (/var/task/.next/server/chunks/549.js:58:629211)
    at t (/var/task/.next/server/webpack-runtime.js:1:205)
    at 2174 (/var/task/.next/server/chunks/549.js:74:78855)
    at t (/var/task/.next/server/webpack-runtime.js:1:205)
    at 86336 (/var/task/.next/server/chunks/228.js:1:239)
    at Object.t [as require] (/var/task/.next/server/webpack-runtime.js:1:205)
    at <unknown> (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:127:1282) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/var/task/.next/server/chunks/cardano_multiplatform_lib_bg.wasm',
  digest: '635065260'
}
```

Can anyone help me resolve the above issue?
Thanks!

**Comment by kozer** [comment]
For anyone interested, this, solved the issue:

```
import { NextConfig } from "next";

const nextConfig: NextConfig = {
  serverExternalPackages: [
    "@blockfrost/blockfrost-js",
    "@jpg-store/lucid-cardano",
    "mongoose",
    "@meshsdk/core",
    "@meshsdk/core-csl",
    "@sidan-lab/sidan-csl-rs-browser",
    "@lucid-evolution/lucid",
    "cardano-multiplatform-lib",
  ],
  webpack(config, { isServer }) {
    config.experiments = {
      ...config.experiments,
      asyncWebAssembly: true,
      layers: true,
    };

    return config;
  },
};

export default nextConfig;
```
